[package]
name = "httparena-wtx-ws"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { default-features = false, features = ["full"], version = "1.0" }
wtx = { default-features = false, features = ["crypto-ring", "optimizations-std", "tokio", "web-socket-server-framework"], version = "0.48" }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
